### ISSUE TITLE
PR 请求：中文README，action

### ISSUE THREAD

**Issue by RexWzh** [huangwb8/m2w#11]
苯苯开发的这个工具太赞了！！

仓库有两个地方值得提 PR ，先开 Issue 看有没兴趣，确定我再来写写。

一是仓库的 README
- 英文版的内容比较简洁清楚，中文版本的内容没有同步过来
- Rest API 的部分可以写在后边，先贴代码，在解释怎么设置获取

二是自动化脚本
GitHub Action 可以做很多事情，比如
1. 通过创建 tag 触发 Python 包的构建脚本，并向 PyPi 同步
2. 自动化测试，比如创建 `tests/` 文件夹，测试可以用苯苯的测试站，密钥等的变量可以在仓库设置
3. 如果写了测试，也可以考虑使用 CodeCov

> 测试文件还可以演示工具用法，用户看测试样例就知道怎么用了

---

个人以前用 hexo 静态博客，博客文件都是 Markdown，通过 GitHub 在多个设备同步。苯苯这个工具很好解决了 hexo 到 wordpress 的过渡问题~感谢(￣▽￣)~*

**Comment by huangwb8** [comment]
谢谢大佬提醒，我之后了解一下 (ฅ´ω`ฅ)
