### ISSUE TITLE
python版本3.7.4目前好像不能适用了

### ISSUE THREAD

**Issue by funcfang** [huangwb8/m2w#5]
Python 3.7.4 is the version I use m2w. I'm not sure whether it could work well in more advanced Python versions.
python_requires='>=3.7.4'
![image](https://user-images.githubusercontent.com/68361120/220681734-b7b505ad-eaa9-4e29-b268-b1436bc84e1b.png)

![1677079317511](https://user-images.githubusercontent.com/68361120/220667897-57939cf3-40ca-43dc-beb2-f23a3a7f4abc.png)
海象算子:=是3.8开始引入的，readme这部分可能需要改下。

**Comment by huangwb8** [comment]
@funcfang 谢谢提醒！WordPress REST API 这部分代码由 @FoxSuzuran 开发，我暂时只在python 3.10中进行测试，我之后应该还会进一步规范代码和文件结构，所以我仅将m2w v2.5标记为pre-release，并未正式投入使用。m2w的文档也还没有完善。

由于m2w v2.2.11的性能已经非常稳定（只是不支持REST API），加上最近有其它事忙，所以并没有很着急地要快速完成m2w 2.5的开发。请多多见谅哈！

您可以先使用m2w v2.2.11 （latest release）。

**Comment by FoxSuzuran** [comment]
抱歉，写的时候忘记了海象的低版本不兼容问题，只考虑了asyncio的兼容性，下次发布前会在3.7+版本进行测试
