### ISSUE TITLE
报403错误

### ISSUE THREAD

**Issue by lixiao888** [huangwb8/m2w#9]
FAILED to connect to your WordPress website: <ProtocolError for xxx.com//xmlrpc.php: 403 Forbidden>

**Comment by huangwb8** [comment]
@lixiao888 

该错误是否还存在？这一般是由帐号/密码错误或网络环境造成。请仔细检查帐号/密码是否错误；网络环境是否使用了代理等。

**Comment by huangwb8** [comment]
@lixiao888 

[m2w v2.5.7](https://github.com/huangwb8/m2w/releases/tag/v2.5.7)已经比较完美，支持REST API和Password模式。感兴趣可以尝试！
